name: Herobrine
main: net.theprogrammersworld.herobrine.Herobrine
version: 2.4.4-SNAPSHOT
description: "Bring Herobrine to your Spigot-based Minecraft server!"
website: https://www.theprogrammersworld.net
api-version: '1.20'
load: STARTUP
commands:
    herobrine:
      description: Main command.
      usage: /herobrine help
      aliases: [hero, hb]