name: Herobrine
main: net.theprogrammersworld.herobrine.Herobrine
version: 2.6.0-SNAPSHOT
description: "Herobrine plugin for Spigot (forked from David-B/herobrine-2) ."
website: https://github.com/furplag/Herobrine/
api-version: 1.19
load: STARTUP
commands:
    herobrine:
      description: Main command.
      usage: /herobrine help
      aliases: [hero, hb]